format = """
$directory $git_branch$git_status $time$character
"""

[character]
disabled = false
success_symbol = '[](bright-yellow bold)'
error_symbol = '[](bright-red bold)'

[directory]
truncation_length = 2
style = "bright-yellow"

[git_branch]
style = "bright-purple bold italic"

[git_status]
style = "bright-red bold italic"

[time]
disabled = false
format = "[$time ]($style)"
time_format = "%R"
style = "bright-yellow bold"
